all:
	gcc S0.c -o S0.out -lpthread
	gcc S1.c -o S1.out -lpthread
	gcc S2.c -o S2.out -lpthread
	gcc S3.c -o S3.out -lpthread
	gcc F.c -o F.out -lpthread
	gcc client.c -o client -lpthread
clean:
	rm -f S*.out F.out *USD-PATH client