all:
	gcc server-cncnt.c -o server-cncnt
	gcc client-cncnt.c -o client-cncnt
	gcc server-cnctless.c -o server-cnctless
	gcc client-cnctless.c -o client-cnctless
	
clean:
	rm -f server-cncnt client-cncnt client-cnctless server-cnctless