CC=gcc
all: P1 P2 P3 P4 delete_queue 
P1: P1.c
	$(CC) P1.c -o P1
P2: P2.c
	$(CC) P2.c -o P2
P3: P3.c
	$(CC) P3.c -o P3
P4: P4.c
	$(CC) P4.c -o P4
delete_queue: delete_queue.c
	$(CC) delete_queue.c -o delete_queue