CC=gcc
all: sender reciever
sender:sender.c
	$(CC) sender.c -o sender
reciever:reciever.c
	$(CC) reciever.c -o reciever
clean:
	rm -f sender reciever
delete_queue: delete_queue.c
	$(CC) delete_queue.c -o delete_queue